/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Header from "../components/Header";
import HeroComponent from "../components/HeroComponent";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import { useMediaQuery } from "react-responsive";

const Desktop = ({ children }) => {
  const isDesktop = useMediaQuery({ minWidth: 992 });
  return isDesktop ? children : null;
};
const Tablet = ({ children }) => {
  const isTablet = useMediaQuery({ minWidth: 768, maxWidth: 991 });
  return isTablet ? children : null;
};
const Mobile = ({ children }) => {
  const isMobile = useMediaQuery({ maxWidth: 767 });
  return isMobile ? children : null;
};

export default function Home() {
  const router = useRouter();
  const newTab = () => {
    window.open("https://amazon-clone-git-main-intiaj.vercel.app/", "_blank");
  };
  const newTab1 = () => {
    window.open("https://medium-clone-ten.vercel.app", "_blank");
  };
  const newTab2 = () => {
    window.open("https://krishworks-frontend-assignment.vercel.app/", "_blank");
  };
  return (
    <>
      <Desktop>
        <div>
          <Head>
            <title>{`Intiaj's Portfolio`}</title>
            <meta name="description" content="Generated by create next app" />
          </Head>

          <Header home="true" />

          <main>
            <div className="h-auto pt-8">
              <HeroComponent />
            </div>

            <div className="py-48 bg-violet-700 ">
              <h1 className="text-center text-4xl font-bold text-white">
                Hi, I’m Intiaj. Nice to meet you.
              </h1>
              <h2 className="text-white text-xl mx-80 py-8 font-semibold text-center">
                I can conjur a website from nothing into existence, fully
                formed. I do not use tricks, nor is this magic. I specialize in
                manipulating the very fabric of the web, its raw materials of
                HTML, CSS, JavaScript, and SVG. I can plan, design, build,
                launch, and maintain a website myself—did I mention that I build
                mobile apps too?
              </h2>
            </div>

            <div className="max-w-7xl mx-auto relative ">
              <div className="absolute -top-36 bg-white rounded-2xl shadow-lg ">
                <div className="border border-violet-300 rounded-2xl grid grid-cols-3 gap-3 justify-items-center">
                  <div className="py-12">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                      />
                    </svg>

                    <h1 className="text-2xl font-bold py-4 text-center">
                      Designer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I value simple content structure, clean design patterns,
                      and thoughtful interactions.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Things I enjoy designing:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      UX, UI, Web, Mobile, Apps, Logos
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Design Tools I Use:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Figma
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Balsamiq Mockups
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Adobe XD
                    </h2>
                  </div>

                  <div className="py-12">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
                      />
                    </svg>

                    <h1 className="text-2xl font-bold py-4 text-center">
                      Front-end Developer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I like to code things from scratch, and enjoy bringing
                      ideas to life in the browser.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Languages I write:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      HTML, CSS, JavaScript, JSX, TypeScript, React JS
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Dev Tools:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      VS Code
                    </h2>

                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Tailwind CSS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Bootstrap
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      React JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Next JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      GitHub
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      ESLint
                    </h2>
                  </div>

                  <div className="py-12">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"
                      />
                    </svg>
                    <h1 className="text-2xl font-bold py-4 text-center">
                      Back-end Developer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I like to keep Back-end simple with efficiency in mind.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Services I use:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      Firebase, MongoDB, Moralis, Sanity io
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Tools I Use:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Node JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Express.js
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Vercel
                    </h2>
                  </div>
                </div>
              </div>
            </div>

            <div className="pt-96 mt-96">
              <div>
                <h1 className="text-center text-3xl font-bold text-violet-400">
                  My Recent Work
                </h1>
                <h2 className="text-center text-xl pt-4 font-semibold text-gray-500">
                  Here are a few projects I've worked on recently.{" "}
                </h2>
              </div>

              <div
                className="my-24 grid grid-cols-3 max-w-7xl mx-auto gap-8
          justify-items-center pb-24"
              >
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center"
                >
                  <img
                    onClick={() => newTab()}
                    className="bg-cyan-500 mt-1 w-80 h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/amazon.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Amazon Clone
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Firebase Firestore & Auth, Stripe
                    API, Tailwind CSS
                  </h2>
                </motion.div>
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center"
                >
                  <img
                    onClick={() => newTab1()}
                    className="bg-cyan-500 w-80 h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/medium.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Medium Clone
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Firebase Auth, Sanity DB,
                    Tailwind CSS
                  </h2>
                </motion.div>
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center"
                >
                  <img
                    onClick={() => newTab2()}
                    className="bg-cyan-500 w-80 h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/qwerty.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Patient Detail Page UI
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Tailwind CSS
                  </h2>
                </motion.div>
              </div>

              <div className="max-w-7xl mx-auto relative">
                <div
                  className="max-w-7xl mx-auto absolute -top-16
         bg-violet-900 rounded-2xl grid grid-cols-3 justify-items-center
          justify-center gap-8 py-12"
                >
                  <h1 className="text-3xl font-bold text-white text-center">
                    Start a project
                  </h1>
                  <h1 className="text-xl font-semibold text-white text-center">
                    Interested in working together? We should queue up a chat.
                  </h1>
                  <button
                    onClick={() => router.push("projectPlanner")}
                    className="border-2 border-violet-400 p-4 rounded-full text-xl
                 font-bold text-white hover:bg-white hover:text-violet-600"
                  >
                    Let's do this
                  </button>
                </div>
              </div>
            </div>
          </main>

          <footer className="bg-violet-500 ">
            <h1 className="text-center pt-36 text-3xl font-bold text-white">
              Intiaj
            </h1>
            <h1 className="text-center pt-8 text-xl font-semibold text-white">
              Living, learning, & leveling up one day at a time.
            </h1>

            <div className="max-w-xl mx-auto py-12 flex justify-center items-center">
              <img
                onClick={() => window.open("https://github.com/Intiaj")}
                src="/github.svg"
                className="h-12 w-12 mx-4 hover:bg-white rounded-full cursor-pointer"
                alt=""
              />
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-14 w-14 mx-4 hover:text-white cursor-pointer"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                />
              </svg>
            </div>

            <h1 className="text-center text-gray-300 font-semibold brightness-75">
              Handcrafted by me
            </h1>

            <div className="flex justify-center items-center py-12 brightness-75">
              <h1 className="text-center font-semibold text-gray-300 pr-4">
                Made with{" "}
              </h1>
              <img
                src="next-js.svg"
                className="h-12 bg-white rounded-full"
                alt=""
              />
              <h1 className="text-center font-semibold text-gray-300 pl-4">
                {" "}
                and{" "}
              </h1>
              <img
                className="h-12 w-36 ml-4 p-2 bg-white rounded-full"
                src="/tailwind-css-wordmark.svg"
                alt=""
              />
            </div>
          </footer>
        </div>
      </Desktop>

      <Tablet>
        <div>
          <Head>
            <title>{`Intiaj's Portfolio`}</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <div className="px-8">
            <Header home="true" />
          </div>

          <main className="">
            <div className="max-w-2xl mx-auto pt-8">
              <HeroComponent />
            </div>

            <div className="py-24 bg-violet-700 ">
              <h1 className="text-center text-4xl font-bold text-white">
                Hi, I’m Intiaj. Nice to meet you.
              </h1>
              <h2 className="text-white text-xl mx-12 py-8 font-semibold text-center">
                I can conjur a website from nothing into existence, fully
                formed. I do not use tricks, nor is this magic. I specialize in
                manipulating the very fabric of the web, its raw materials of
                HTML, CSS, JavaScript, and SVG. I can plan, design, build,
                launch, and maintain a website myself—did I mention that I build
                mobile apps too?
              </h2>
            </div>

            <div className="max-w-3xl mx-auto relative ">
              <div className="absolute -top-20 bg-white rounded-2xl shadow-lg ">
                <div className="border border-violet-300 rounded-2xl grid grid-cols-3 gap-3 justify-items-center">
                  <div className="py-12">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                      />
                    </svg>

                    <h1 className="text-2xl font-bold py-4 text-center">
                      Designer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I value simple content structure, clean design patterns,
                      and thoughtful interactions.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Things I enjoy designing:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      UX, UI, Web, Mobile, Apps, Logos
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Design Tools I Use:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Figma
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Balsamiq Mockups
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Adobe XD
                    </h2>
                  </div>

                  <div className="py-12">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
                      />
                    </svg>

                    <h1 className="text-2xl font-bold py-4 text-center">
                      Front-end Developer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I like to code things from scratch, and enjoy bringing
                      ideas to life in the browser.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Languages I write:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      HTML, CSS, JavaScript, JSX, TypeScript, React JS
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Dev Tools:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      VS Code
                    </h2>

                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Tailwind CSS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Bootstrap
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      React JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Next JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      GitHub
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      ESLint
                    </h2>
                  </div>

                  <div className="py-12">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"
                      />
                    </svg>
                    <h1 className="text-2xl font-bold py-4 text-center">
                      Back-end Developer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I like to keep Back-end simple with efficiency in mind.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Services I use:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      Firebase, MongoDB, Moralis, Sanity io
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Tools I Use:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Node JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Express.js
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Vercel
                    </h2>
                  </div>
                </div>
              </div>
            </div>

            <div className="pt-96 mt-96">
              <div className="h-48" />
              <div>
                <h1 className="text-center text-3xl font-bold text-violet-400">
                  My Recent Work
                </h1>
                <h2 className="text-center text-xl pt-4 font-semibold text-gray-500">
                  Here are a few projects I've worked on recently.{" "}
                </h2>
              </div>

              <div
                className="my-24 grid grid-cols-2 max-w-3xl mx-auto gap-8
          justify-items-center pb-24"
              >
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center"
                >
                  <img
                    onClick={() => newTab()}
                    className="bg-cyan-500 mt-1 w-full h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/amazon.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Amazon Clone
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Firebase Firestore & Auth, Stripe
                    API, Tailwind CSS
                  </h2>
                </motion.div>
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center"
                >
                  <img
                    onClick={() => newTab1()}
                    className="bg-cyan-500 w-full h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/medium.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Medium Clone
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Firebase Auth, Sanity DB,
                    Tailwind CSS
                  </h2>
                </motion.div>
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center"
                >
                  <img
                    onClick={() => newTab2()}
                    className="bg-cyan-500 w-full h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/web3.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    WEB 3.0 Chat App
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Moralis, Tailwind CSS
                  </h2>
                </motion.div>
              </div>

              <div className="max-w-3xl mx-auto relative">
                <div
                  className="max-w-3xl mx-auto absolute -top-16 
         bg-violet-900 rounded-2xl grid grid-cols-3 justify-items-center
           gap-8 py-8"
                >
                  <h1 className="text-3xl font-bold text-white text-center">
                    Start a project
                  </h1>
                  <h1 className="text-xl font-semibold text-white text-center">
                    Interested in working together? We should queue up a chat.
                  </h1>
                  <button
                    onClick={() => router.push("projectPlanner")}
                    className="border-2 border-violet-400 p-4 rounded-full text-xl
                 font-bold text-white hover:bg-white hover:text-violet-600"
                  >
                    Let's do this
                  </button>
                </div>
              </div>
            </div>
          </main>

          <footer className="bg-violet-500 ">
            <h1 className="text-center pt-36 text-3xl font-bold text-white">
              Intiaj
            </h1>
            <h1 className="text-center pt-8 text-xl font-semibold text-white">
              Living, learning, & leveling up one day at a time.
            </h1>

            <div className="max-w-xl mx-auto py-12 flex justify-center items-center">
              <img
                onClick={() => window.open("https://github.com/Intiaj")}
                src="/github.svg"
                className="h-12 w-12 mx-4 hover:bg-white rounded-full cursor-pointer"
                alt=""
              />
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-14 w-14 mx-4 hover:text-white cursor-pointer"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                />
              </svg>
            </div>

            <h1 className="text-center text-gray-300 font-semibold brightness-75">
              Handcrafted by me
            </h1>

            <div className="flex justify-center items-center py-12 brightness-75">
              <h1 className="text-center font-semibold text-gray-300 pr-4">
                Made with{" "}
              </h1>
              <img
                src="next-js.svg"
                className="h-12 bg-white rounded-full"
                alt=""
              />
              <h1 className="text-center font-semibold text-gray-300 pl-4">
                {" "}
                and{" "}
              </h1>
              <img
                className="h-12 w-36 ml-4 p-2 bg-white rounded-full"
                src="/tailwind-css-wordmark.svg"
                alt=""
              />
            </div>
          </footer>
        </div>
      </Tablet>

      <Mobile>
        <div>
          <Head>
            <title>{`Intiaj's Portfolio`}</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <div className="px-8">
            <Header home="true" />
          </div>

          <main>
            <div className="max-w-md mx-auto pt-8">
              <HeroComponent />
            </div>

            <div className="py-20 px-8 bg-violet-700 ">
              <h1 className="text-center text-3xl font-bold text-white">
                Hi, I’m Intiaj. Nice to meet you.
              </h1>
              <h2 className="text-white text-lg py-8 font-semibold text-center">
                I can conjur a website from nothing into existence, fully
                formed. I do not use tricks, nor is this magic. I specialize in
                manipulating the very fabric of the web, its raw materials of
                HTML, CSS, JavaScript, and SVG. I can plan, design, build,
                launch, and maintain a website myself—did I mention that I build
                mobile apps too?
              </h2>
            </div>

            <div className=" relative ">
              <div className="absolute -top-20 bg-white rounded-2xl shadow-lg mx-4">
                <div className="border border-violet-300 rounded-2xl grid grid-cols-1 gap-3 justify-items-center p-2">
                  <div className="py-8">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                      />
                    </svg>

                    <h1 className="text-2xl font-bold py-4 text-center">
                      Designer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I value simple content structure, clean design patterns,
                      and thoughtful interactions.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Things I enjoy designing:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      UX, UI, Web, Mobile, Apps, Logos
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Design Tools I Use:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Figma
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Balsamiq Mockups
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Adobe XD
                    </h2>
                  </div>

                  <div className="py-8">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
                      />
                    </svg>

                    <h1 className="text-2xl font-bold py-4 text-center">
                      Front-end Developer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I like to code things from scratch, and enjoy bringing
                      ideas to life in the browser.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Languages I write:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      HTML, CSS, JavaScript, JSX, TypeScript, React JS
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Dev Tools:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      VS Code
                    </h2>

                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Tailwind CSS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Bootstrap
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      React JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Next JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      GitHub
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      ESLint
                    </h2>
                  </div>

                  <div className="py-8">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-20 w-20 text-violet-500 mx-auto"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"
                      />
                    </svg>
                    <h1 className="text-2xl font-bold py-4 text-center">
                      Back-end Developer
                    </h1>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      I like to keep Back-end simple with efficiency in mind.
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                      Services I use:
                    </h3>
                    <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                      Firebase, MongoDB, Moralis, Sanity io
                    </h2>

                    <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                      Tools I Use:
                    </h3>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Node JS
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Express.js
                    </h2>
                    <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                      Vercel
                    </h2>
                  </div>
                </div>
              </div>
            </div>

            <div className="pt-96 mt-96">
              <div className="h-96" />
              <div className="h-96" />
              <div className="h-96" />
              <div className="h-72" />
              <div>
                <h1 className="text-center text-3xl font-bold text-violet-400">
                  My Recent Work
                </h1>
                <h2 className="text-center text-xl pt-4 font-semibold text-gray-500">
                  Here are a few projects I've worked on recently.{" "}
                </h2>
              </div>

              <div
                className="my-24 grid grid-cols-1 mx-4 gap-8
          justify-items-center pb-16"
              >
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center "
                >
                  <img
                    onClick={() => newTab()}
                    className="bg-cyan-500 mt-1 w-full h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/amazon.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Amazon Clone
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Firebase Firestore & Auth, Stripe
                    API, Tailwind CSS
                  </h2>
                </motion.div>
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center pt-4"
                >
                  <img
                    onClick={() => newTab1()}
                    className="bg-cyan-500 w-full h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/medium.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Medium Clone
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Firebase Auth, Sanity DB,
                    Tailwind CSS
                  </h2>
                </motion.div>
                <motion.div
                  whileHover={{ y: [0, -15, 0, -15, 0] }}
                  className="flex flex-col justify-center items-center pt-4"
                >
                  <img
                    onClick={() => newTab2()}
                    className="bg-cyan-500 w-full h-38 rounded-2xl hover:brightness-75 cursor-pointer 
            shadow-md hover:shadow-lg hover:shadow-fuchsia-200"
                    src="/web3.png"
                    alt=""
                  />
                  <h1 className="text-center text-lg font-semibold text-gray-500 py-2">
                    Patient Detail Page
                  </h1>
                  <h2 className="text-center text-sm text-gray-500 font-medium">
                    {" "}
                    made with React + Next JS, Tailwind CSS
                  </h2>
                </motion.div>
              </div>

              <div className="relative mx-4">
                <div
                  className="absolute -top-16 
         bg-violet-900 rounded-2xl grid grid-cols-1 justify-items-center
           gap-8 py-8"
                >
                  <h1 className="text-3xl font-bold text-white text-center">
                    Start a project
                  </h1>
                  <h1 className="text-xl font-semibold text-white text-center">
                    Interested in working together? We should queue up a chat.
                  </h1>
                  <button
                    onClick={() => router.push("projectPlanner")}
                    className="border-2 border-violet-400 p-4 rounded-full text-xl
                 font-bold text-white hover:bg-white hover:text-violet-600"
                  >
                    Let's do this
                  </button>
                </div>
              </div>
            </div>
          </main>

          <footer className="bg-violet-500 pt-48 px-4">
            <h1 className="text-center pt-36 text-3xl font-bold text-white">
              Intiaj
            </h1>
            <h1 className="text-center pt-8 text-xl font-semibold text-white">
              Living, learning, & leveling up one day at a time.
            </h1>

            <div className="max-w-xl mx-auto py-12 flex justify-center items-center">
              <img
                onClick={() => window.open("https://github.com/Intiaj")}
                src="/github.svg"
                className="h-12 w-12 mx-4 hover:bg-white rounded-full cursor-pointer"
                alt=""
              />
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-14 w-14 mx-4 hover:text-white cursor-pointer"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                />
              </svg>
            </div>

            <h1 className="text-center text-gray-300 font-semibold brightness-75">
              Handcrafted by me
            </h1>

            <div className="flex justify-center items-center py-12 brightness-75">
              <h1 className="text-center font-semibold text-gray-300 pr-4">
                Made with{" "}
              </h1>
              <img
                src="next-js.svg"
                className="h-12 bg-white rounded-full"
                alt=""
              />
              <h1 className="text-center font-semibold text-gray-300 pl-4">
                {" "}
                and{" "}
              </h1>
              <img
                className="h-12 w-36 ml-4 p-2 bg-white rounded-full"
                src="/tailwind-css-wordmark.svg"
                alt=""
              />
            </div>
          </footer>
        </div>
      </Mobile>
    </>
  );
}
