/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Header from "../components/Header";
import HeroComponent from "../components/HeroComponent";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>{`Intiaj's Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <div className="max-w-7xl mx-auto pt-8">
          <HeroComponent />
        </div>

        <div className="py-48 bg-violet-700 ">
          <h1 className="text-center text-4xl font-bold text-white">
            Hi, I’m Intiaj. Nice to meet you.
          </h1>
          <h2 className="text-white text-xl mx-80 py-8 font-semibold text-center">
            Since beginning my journey as a freelance designer nearly 10 years
            ago, I've done remote work for agencies, consulted for startups, and
            collaborated with talented people to create digital products for
            both business and consumer use. I'm quietly confident, naturally
            curious, and perpetually working on improving my chops one design
            problem at a time.
          </h2>
        </div>

        <div className="max-w-7xl mx-auto relative ">
          <div className="absolute -top-36 bg-white rounded-2xl shadow-lg ">
            <div className="border border-violet-300 rounded-2xl grid grid-cols-3 gap-3 justify-items-center">
              <div className="py-12">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-20 w-20 text-violet-500 mx-auto"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                  />
                </svg>

                <h1 className="text-2xl font-bold py-4 text-center">
                  Designer
                </h1>
                <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                  I value simple content structure, clean design patterns, and
                  thoughtful interactions.
                </h2>

                <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                  Things I enjoy designing:
                </h3>
                <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                  UX, UI, Web, Mobile, Apps, Logos
                </h2>

                <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                  Design Tools I Use:
                </h3>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
              </div>

              <div className="py-12">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-20 w-20 text-violet-500 mx-auto"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
                  />
                </svg>

                <h1 className="text-2xl font-bold py-4 text-center">
                  Designer
                </h1>
                <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                  I value simple content structure, clean design patterns, and
                  thoughtful interactions.
                </h2>

                <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                  Things I enjoy designing:
                </h3>
                <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                  UX, UI, Web, Mobile, Apps, Logos
                </h2>

                <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                  Design Tools I Use:
                </h3>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
              </div>

              <div className="py-12">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-20 w-20 text-violet-500 mx-auto"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
                  />
                </svg>
                <h1 className="text-2xl font-bold py-4 text-center">
                  Designer
                </h1>
                <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                  I value simple content structure, clean design patterns, and
                  thoughtful interactions.
                </h2>

                <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center">
                  Things I enjoy designing:
                </h3>
                <h2 className="text-lg font-semibold py-4 text-center text-gray-600">
                  UX, UI, Web, Mobile, Apps, Logos
                </h2>

                <h3 className="text-violet-500 text-xl font-semibold pt-12 text-center pb-2">
                  Design Tools I Use:
                </h3>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
                <h2 className="text-gray-600 text-center text-lg font-semibold py-2">
                  Balsamiq Mockups
                </h2>
              </div>
            </div>
          </div>
        </div>

        <div className="pt-96 mt-96">
          <div>
            <h1 className="text-center text-3xl font-bold text-violet-400">
              My Recent Work
            </h1>
            <h2 className="text-center text-xl pt-4 font-semibold text-gray-500">
              Here are a few design projects I've worked on recently.{" "}
            </h2>
          </div>

          <div
            className="my-24 grid grid-cols-3 max-w-7xl mx-auto gap-8 
          justify-items-center pb-24"
          >
            <div className="bg-cyan-500 w-64 h-36 rounded-2xl" />
            <div className="bg-cyan-500 w-64 h-36 rounded-2xl" />
            <div className="bg-cyan-500 w-64 h-36 rounded-2xl" />
          </div>

          <div className="max-w-7xl mx-auto relative">
            <div
              className="max-w-7xl mx-auto absolute -top-16
         bg-violet-900 rounded-2xl grid grid-cols-3 justify-items-center
          justify-center gap-8 py-12"
            >
              <h1 className="text-3xl font-bold text-white text-center">
                Start a project
              </h1>
              <h1 className="text-xl font-semibold text-white text-center">
                Interested in working together? We should queue up a chat.
              </h1>
              <button
                onClick={() => router.push("projectPlanner")}
                className="border-2 border-violet-400 p-4 rounded-full text-xl font-bold text-white"
              >
                Let's do this
              </button>
            </div>
          </div>
        </div>
      </main>

      <footer className="bg-violet-500 ">
        <h1 className="text-center pt-36 text-3xl font-bold text-white">
          Intiaj
        </h1>
        <h1 className="text-center pt-8 text-xl font-semibold text-white">
          Living, learning, & leveling up one day at a time.
        </h1>

        <div className="max-w-xl mx-auto py-12 flex justify-center items-center">
          <img
            src="/github.svg"
            className="h-12 w-12 mx-4 hover:bg-white rounded-full cursor-pointer"
            alt=""
          />
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-14 w-14 mx-4 hover:text-white cursor-pointer"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
            />
          </svg>
        </div>

        <h1 className="text-center text-gray-300 font-semibold brightness-75">
          Handcrafted by me
        </h1>

        <div className="flex justify-center items-center py-12 brightness-75">
          <h1 className="text-center font-semibold text-gray-300 pr-4">
            Made with{" "}
          </h1>
          <img
            src="next-js.svg"
            className="h-12 bg-white rounded-full"
            alt=""
          />
          <h1 className="text-center font-semibold text-gray-300 pl-4">
            {" "}
            and{" "}
          </h1>
          <img
            className="h-12 w-36 ml-4 p-2 bg-white rounded-full"
            src="/tailwind-css-wordmark.svg"
            alt=""
          />
        </div>
      </footer>
    </div>
  );
}
